/**
 * The deployment artifacts, defined once.
 *
 * `plugin/.mcp.json` and `codex-plugin/.mcp.json` run `dist/clanker-mcp.mjs`
 * — the COMMITTED bundle, not a build output produced at install time. What is
 * in git is what the host executes, so a bundle that lags `src/` is a shipped
 * server that lags the reviewed source. #19 landed with exactly that: the
 * committed bundles still registered the generic `clanker_start` entrance that
 * the source had deleted, so merging would have deployed none of the narrow
 * per-profile tools and left the forgeable entrance alive.
 *
 * This module is the single definition of the artifact set. `npm run bundle`
 * builds from it, and test/bundle-sync.test.ts rebuilds from it and compares
 * against what is committed — so the gate cannot disagree with the build about
 * which flags or entrypoints are "correct". Adding an artifact here gives it
 * both a build and a staleness gate at once.
 */
import { spawnSync } from "node:child_process";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** esbuild flags shared by every artifact. */
export const ESBUILD_FLAGS = ["--bundle", "--platform=node", "--format=esm", "--target=node20"];

/**
 * One entry per generated file. `name` is the filename inside each plugin's
 * `dist/`; the same three artifacts are emitted into every dir in
 * `PLUGIN_DIST_DIRS`, byte-identical (host selection is a runtime `--host`
 * argument, not a build variant).
 */
export interface Bundle {
  /** Filename inside each plugin's `dist/`. */
  readonly name: string;
  /** Entrypoint, relative to the repo root. */
  readonly entry: string;
  /** Banner esbuild prepends, telling a reader the file is generated. */
  readonly banner: string;
}

export const BUNDLES: readonly Bundle[] = [
  {
    name: "clanker-mcp.mjs",
    entry: "src/index.ts",
    banner: "// GENERATED by 'npm run bundle' (esbuild). Do not edit — edit src/ and rebuild.",
  },
  {
    name: "codex-acp.mjs",
    entry: "node_modules/@agentclientprotocol/codex-acp/dist/index.js",
    banner: "// GENERATED from pinned @agentclientprotocol/codex-acp by 'npm run bundle'. Do not edit.",
  },
  {
    name: "gemini-acp.mjs",
    entry: "src/gemini-acp.ts",
    banner: "// GENERATED Gemini reconnaissance ACP sidecar. Do not edit.",
  },
];

/** Every plugin adapter that ships a copy of the artifacts. */
export const PLUGIN_DIST_DIRS: readonly string[] = ["plugin/dist", "codex-plugin/dist"];

/**
 * Builds one artifact to `outfile`.
 *
 * Always runs from the repo root: esbuild writes source-relative path comments
 * into the bundle, so the cwd is part of the output. A rebuild from anywhere
 * else would differ from the committed artifact for a reason that has nothing
 * to do with the source.
 */
export function buildBundle(bundle: Bundle, outfile: string): string {
  const result = spawnSync(
    join(REPO_ROOT, "node_modules/.bin/esbuild"),
    [bundle.entry, ...ESBUILD_FLAGS, `--outfile=${outfile}`, `--banner:js=${bundle.banner}`],
    { cwd: REPO_ROOT, encoding: "utf8" },
  );
  if (result.status !== 0) {
    throw new Error(`esbuild failed for ${bundle.entry} -> ${outfile}\n${result.stderr || result.error?.message || ""}`);
  }
  return outfile;
}

function main(): void {
  for (const dir of PLUGIN_DIST_DIRS) {
    for (const bundle of BUNDLES) {
      buildBundle(bundle, join(REPO_ROOT, dir, bundle.name));
    }
    console.log(`Bundled ${BUNDLES.length} artifacts into ${dir}`);
  }
}

// Importable by the staleness gate; executable as `npm run bundle`.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
